/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVoiceRouteImport } from './routes/dashboard.voice'
import { Route as DashboardV2RouteImport } from './routes/dashboard.v2'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSerialRouteImport } from './routes/dashboard.serial'
import { Route as DashboardSensorsRouteImport } from './routes/dashboard.sensors'
import { Route as DashboardSelfgraphRouteImport } from './routes/dashboard.selfgraph'
import { Route as DashboardPulseRouteImport } from './routes/dashboard.pulse'
import { Route as DashboardPrivacyRouteImport } from './routes/dashboard.privacy'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard.onboarding'
import { Route as DashboardNpuRouteImport } from './routes/dashboard.npu'
import { Route as DashboardMigrationRouteImport } from './routes/dashboard.migration'
import { Route as DashboardMetricsRouteImport } from './routes/dashboard.metrics'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardDreamRouteImport } from './routes/dashboard.dream'
import { Route as DashboardDevicesRouteImport } from './routes/dashboard.devices'
import { Route as DashboardArchitectureRouteImport } from './routes/dashboard.architecture'
import { Route as DashboardAlertsRouteImport } from './routes/dashboard.alerts'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoiceRoute = DashboardVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardV2Route = DashboardV2RouteImport.update({
  id: '/v2',
  path: '/v2',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSerialRoute = DashboardSerialRouteImport.update({
  id: '/serial',
  path: '/serial',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSensorsRoute = DashboardSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSelfgraphRoute = DashboardSelfgraphRouteImport.update({
  id: '/selfgraph',
  path: '/selfgraph',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPulseRoute = DashboardPulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPrivacyRoute = DashboardPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNpuRoute = DashboardNpuRouteImport.update({
  id: '/npu',
  path: '/npu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrationRoute = DashboardMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMetricsRoute = DashboardMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDreamRoute = DashboardDreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevicesRoute = DashboardDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardArchitectureRoute = DashboardArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/dream': typeof DashboardDreamRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/migration': typeof DashboardMigrationRoute
  '/dashboard/npu': typeof DashboardNpuRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/pulse': typeof DashboardPulseRoute
  '/dashboard/selfgraph': typeof DashboardSelfgraphRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/serial': typeof DashboardSerialRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/v2': typeof DashboardV2Route
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/dream': typeof DashboardDreamRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/migration': typeof DashboardMigrationRoute
  '/dashboard/npu': typeof DashboardNpuRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/pulse': typeof DashboardPulseRoute
  '/dashboard/selfgraph': typeof DashboardSelfgraphRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/serial': typeof DashboardSerialRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/v2': typeof DashboardV2Route
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/alerts': typeof DashboardAlertsRoute
  '/dashboard/architecture': typeof DashboardArchitectureRoute
  '/dashboard/devices': typeof DashboardDevicesRoute
  '/dashboard/dream': typeof DashboardDreamRoute
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/metrics': typeof DashboardMetricsRoute
  '/dashboard/migration': typeof DashboardMigrationRoute
  '/dashboard/npu': typeof DashboardNpuRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/privacy': typeof DashboardPrivacyRoute
  '/dashboard/pulse': typeof DashboardPulseRoute
  '/dashboard/selfgraph': typeof DashboardSelfgraphRoute
  '/dashboard/sensors': typeof DashboardSensorsRoute
  '/dashboard/serial': typeof DashboardSerialRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/v2': typeof DashboardV2Route
  '/dashboard/voice': typeof DashboardVoiceRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/architecture'
    | '/dashboard/devices'
    | '/dashboard/dream'
    | '/dashboard/events'
    | '/dashboard/metrics'
    | '/dashboard/migration'
    | '/dashboard/npu'
    | '/dashboard/onboarding'
    | '/dashboard/privacy'
    | '/dashboard/pulse'
    | '/dashboard/selfgraph'
    | '/dashboard/sensors'
    | '/dashboard/serial'
    | '/dashboard/settings'
    | '/dashboard/v2'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/alerts'
    | '/dashboard/architecture'
    | '/dashboard/devices'
    | '/dashboard/dream'
    | '/dashboard/events'
    | '/dashboard/metrics'
    | '/dashboard/migration'
    | '/dashboard/npu'
    | '/dashboard/onboarding'
    | '/dashboard/privacy'
    | '/dashboard/pulse'
    | '/dashboard/selfgraph'
    | '/dashboard/sensors'
    | '/dashboard/serial'
    | '/dashboard/settings'
    | '/dashboard/v2'
    | '/dashboard/voice'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/alerts'
    | '/dashboard/architecture'
    | '/dashboard/devices'
    | '/dashboard/dream'
    | '/dashboard/events'
    | '/dashboard/metrics'
    | '/dashboard/migration'
    | '/dashboard/npu'
    | '/dashboard/onboarding'
    | '/dashboard/privacy'
    | '/dashboard/pulse'
    | '/dashboard/selfgraph'
    | '/dashboard/sensors'
    | '/dashboard/serial'
    | '/dashboard/settings'
    | '/dashboard/v2'
    | '/dashboard/voice'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voice': {
      id: '/dashboard/voice'
      path: '/voice'
      fullPath: '/dashboard/voice'
      preLoaderRoute: typeof DashboardVoiceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/v2': {
      id: '/dashboard/v2'
      path: '/v2'
      fullPath: '/dashboard/v2'
      preLoaderRoute: typeof DashboardV2RouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/serial': {
      id: '/dashboard/serial'
      path: '/serial'
      fullPath: '/dashboard/serial'
      preLoaderRoute: typeof DashboardSerialRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sensors': {
      id: '/dashboard/sensors'
      path: '/sensors'
      fullPath: '/dashboard/sensors'
      preLoaderRoute: typeof DashboardSensorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/selfgraph': {
      id: '/dashboard/selfgraph'
      path: '/selfgraph'
      fullPath: '/dashboard/selfgraph'
      preLoaderRoute: typeof DashboardSelfgraphRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pulse': {
      id: '/dashboard/pulse'
      path: '/pulse'
      fullPath: '/dashboard/pulse'
      preLoaderRoute: typeof DashboardPulseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/privacy': {
      id: '/dashboard/privacy'
      path: '/privacy'
      fullPath: '/dashboard/privacy'
      preLoaderRoute: typeof DashboardPrivacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/npu': {
      id: '/dashboard/npu'
      path: '/npu'
      fullPath: '/dashboard/npu'
      preLoaderRoute: typeof DashboardNpuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/migration': {
      id: '/dashboard/migration'
      path: '/migration'
      fullPath: '/dashboard/migration'
      preLoaderRoute: typeof DashboardMigrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/metrics': {
      id: '/dashboard/metrics'
      path: '/metrics'
      fullPath: '/dashboard/metrics'
      preLoaderRoute: typeof DashboardMetricsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dream': {
      id: '/dashboard/dream'
      path: '/dream'
      fullPath: '/dashboard/dream'
      preLoaderRoute: typeof DashboardDreamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devices': {
      id: '/dashboard/devices'
      path: '/devices'
      fullPath: '/dashboard/devices'
      preLoaderRoute: typeof DashboardDevicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/architecture': {
      id: '/dashboard/architecture'
      path: '/architecture'
      fullPath: '/dashboard/architecture'
      preLoaderRoute: typeof DashboardArchitectureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alerts': {
      id: '/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardArchitectureRoute: typeof DashboardArchitectureRoute
  DashboardDevicesRoute: typeof DashboardDevicesRoute
  DashboardDreamRoute: typeof DashboardDreamRoute
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardMetricsRoute: typeof DashboardMetricsRoute
  DashboardMigrationRoute: typeof DashboardMigrationRoute
  DashboardNpuRoute: typeof DashboardNpuRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardPrivacyRoute: typeof DashboardPrivacyRoute
  DashboardPulseRoute: typeof DashboardPulseRoute
  DashboardSelfgraphRoute: typeof DashboardSelfgraphRoute
  DashboardSensorsRoute: typeof DashboardSensorsRoute
  DashboardSerialRoute: typeof DashboardSerialRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardV2Route: typeof DashboardV2Route
  DashboardVoiceRoute: typeof DashboardVoiceRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardArchitectureRoute: DashboardArchitectureRoute,
  DashboardDevicesRoute: DashboardDevicesRoute,
  DashboardDreamRoute: DashboardDreamRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardMetricsRoute: DashboardMetricsRoute,
  DashboardMigrationRoute: DashboardMigrationRoute,
  DashboardNpuRoute: DashboardNpuRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardPrivacyRoute: DashboardPrivacyRoute,
  DashboardPulseRoute: DashboardPulseRoute,
  DashboardSelfgraphRoute: DashboardSelfgraphRoute,
  DashboardSensorsRoute: DashboardSensorsRoute,
  DashboardSerialRoute: DashboardSerialRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardV2Route: DashboardV2Route,
  DashboardVoiceRoute: DashboardVoiceRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
